---
name: verify

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1

  golangci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
      - name: Install dependencies
        run: go mod download
      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Generate the code
        run: go generate -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: false
          working-directory: .

  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
      - name: Install dependencies
        run: go mod download
      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Generate the code
        run: go generate -v ./...
      - name: Test with the Go CLI
        run: go test ./...
